### ISSUE TITLE
coros module in gevent-1.1rc1 is depricated

### ISSUE THREAD

**Issue by salsa-dev** [grnet/snf-vncauthproxy#11]
gevent.coros has been renamed to gevent.lock

vncauthproxy throws DeprecationWarning

files affected:
vncauthproxy/websockets.py
vncauthproxy/proxy.py

**Comment by psomas** [comment]
I'll take a look into it. IIRC, we haven't seen this on Jessie (which uses gevent-1.0.1), but (assuming this is the only incompatibility :) it should be easy to make it work with both 1.1+ and earlier versions.

**Comment by skalkoto** [comment]
Fixed with 595609f05dd4470ef697e5b18b248ede5fb0384f
